import type { Metadata } from "next";
import "./globals.css";
import { ScrollArea } from "@/components/ui/scroll-area";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ScrollArea className="h-screen w-full">
          {children}
        </ScrollArea>
      </body>
    </html>
  );
}
